[greeter]
background = /home/max/Pictures/backiee-286513-landscape.jpg
user-background = false
theme-name = Adwaita-dark
icon-theme-name = Adwaita
font-name = Sans 10
indicators = ~clock;~host;~power
clock-format = %H:%M
